CREATE TABLE PORTALADS
(
  URL_ANUNCIO VARCHAR(500)
, FECHA_PROCESADO DATE
, PORTAL VARCHAR(50)
, COD_POSTAL VARCHAR(50)
, MUNICIPIO VARCHAR(100)
, DISTRITO VARCHAR(100)
, BARRIO VARCHAR(100)
, PRECIO DECIMAL(10,2)
, M2 DECIMAL(10,2)
, PRECIOM2 DECIMAL(10,2)
)
;

ALTER TABLE PORTALADS ADD PRIMARY KEY(URL_ANUNCIO, FECHA_PROCESADO);


