CREATE TABLE company
(
  CIF varchar(10)
, EMPRESA varchar(100)
, DIRECCION varchar(500)
, CODPOSTAL varchar(5)
, CODPOBLACION varchar(5)
, POBLACION varchar(100)
, CODPROVINCIA varchar(5)
, PROVINCIA varchar(100)
, TELEFONO varchar(20)
, CNAE varchar(20)
, FUNDACION INTEGER(4)
, TIPOEMPRESA varchar(20)
, VENTASEUROS DOUBLE
, RANGOVENTAS varchar(100)
, EMPLEADOS INTEGER
, ESTRATOASALARIADOS varchar(100)
, PAISMATRIZ varchar(50)
, FECHAPROCESADO DATE
);

ALTER TABLE company ADD PRIMARY KEY(CIF);
ALTER TABLE company ADD CONSTRAINT FK_CNAE FOREIGN KEY (CNAE) REFERENCES cnae(CNAE);

